# Generated by Django 3.2.4 on 2021-06-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
                ('content', models.TextField(max_length=1500, verbose_name='Содержаение')),
                ('file', models.FileField(blank=True, upload_to='file', verbose_name='Файл')),
            ],
        ),
    ]
