# Generated by Django 3.2.4 on 2021-06-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='file',
        ),
        migrations.AddField(
            model_name='questions',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Включать в быстрый доступ'),
        ),
    ]
