# Generated by Django 3.2.4 on 2021-06-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0002_auto_20210628_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание отзыва')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Отображение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='is_urgent',
            new_name='is_visible',
        ),
    ]
