# Generated by Django 3.2.4 on 2021-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0003_auto_20210628_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
