# Generated by Django 3.2.4 on 2021-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0004_questions_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(upload_to='osteom_views/static/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Включить в быстрый доступ'),
        ),
    ]
