# Generated by Django 3.2.4 on 2021-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0008_remove_questions_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='bio',
            field=models.TextField(blank=True, max_length=50, verbose_name='Короткое описание'),
        ),
    ]
