# Generated by Django 3.2.4 on 2021-06-29 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0012_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
