# Generated by Django 3.2.4 on 2021-06-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0014_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='title',
        ),
    ]
