# Generated by Django 3.2.4 on 2021-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0018_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='mail',
            field=models.CharField(default='test_mail@mail.com', max_length=50, verbose_name='Почта для связи'),
        ),
    ]
