# Generated by Django 3.2.4 on 2021-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0020_bio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('free', models.BooleanField(default=False, verbose_name='Бесплатно')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Цены услуг',
            },
        ),
    ]
