# Generated by Django 3.2.4 on 2021-06-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0021_serviceprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(max_length=800, verbose_name='Содержание отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Отображение на главной странице(максимум 5)'),
        ),
    ]
