# Generated by Django 3.2.4 on 2021-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0022_auto_20210630_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_main', models.ImageField(upload_to='osteom_views/static/images/templates', verbose_name='Раздел о враче')),
                ('is_work_main', models.BooleanField(default=False, verbose_name='Отображать img_main')),
                ('img_about', models.ImageField(upload_to='osteom_views/static/images/templates', verbose_name='Раздел сертификаты')),
                ('is_work_about', models.BooleanField(default=False, verbose_name='Отображать img_about')),
                ('img_price', models.ImageField(upload_to='osteom_views/static/images/templates', verbose_name='Раздел цены')),
                ('is_work_price', models.BooleanField(default=False, verbose_name='Отображать img_price')),
                ('img_feedback', models.ImageField(upload_to='osteom_views/static/images/templates', verbose_name='Раздел отзывы')),
                ('is_work_feedback', models.BooleanField(default=False, verbose_name='Отображать img_feedback')),
                ('img_contacts', models.ImageField(upload_to='osteom_views/static/images/templates', verbose_name='Раздел контакты')),
                ('is_work_contacts', models.BooleanField(default=False, verbose_name='Отображать img_contacts')),
            ],
        ),
    ]
