# Generated by Django 3.2.4 on 2021-06-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0023_backgroundphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundPhoto',
        ),
    ]
