# Generated by Django 3.2.4 on 2021-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0025_blogabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogabout',
            name='bio',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
