# Generated by Django 3.2.4 on 2021-07-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0026_alter_blogabout_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAbout',
        ),
    ]
