# Generated by Django 3.2.4 on 2021-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteom_views', '0027_delete_blogabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Из самых последних', max_length=50, verbose_name='Заголовок')),
                ('bio', models.CharField(max_length=500, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='osteom_views/static/images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Био',
                'verbose_name_plural': 'Био',
            },
        ),
    ]
